#!/bin/ash -x
# this script runs on Tiny Core after target machine is set up, captures it

# Using the USB as shuttle, bring the target machine onto the USB stick

# the following config file communicates between desktop and tiny core
source /mnt/sdb2/tce/installer.conf

# are we fetching a netinst, or a configured XSCE
#   hopefully, netinst will never create 3 partitions
umount /dev/sda3
mount /dev/sda3 /mnt/sda3
if [ $? -eq 0 ]; then
   if [ -d /mnt/sda3/cache ]; then 
      umount /dev/sda2
      mount "/dev/sda2" "/mnt/sda2"
      if [ ! $? -eq 0 ];then
	 echo "unable to mount /dev/sda2. quitting"
	 exit 1
      fi
      SOURCEMNT="/mnt/sda2"
      #LIBRARYMNT="/mnt/sda3"
   else
      echo "cannot find /cache on partition 3. Quitting"
      exit 1
   fi
# check to see if sysprep has been executed on the server
#
   if [ ! -h $SOURCEMNT/etc/systemd/system/multi-user.target.wants/finish-install.service ];then
      echo
      echo "Please remember to run 'sysprep' on target before creating image"
      echo
      exit 1
  fi
else # check if this might be a netinst
   # reminder: netinst when using EFI requires first partition to be EFI
   mount /dev/sda1 /mnt/sda1
   if [ $? -eq 0 ];then
	if [ -d /mnt/sda1/usr ];then
	    SOURCEMNT="mnt/sda1"
        fi
        umount /dev/sda1
   fi
   mount /dev/sda2 /mnt/sda2
   if [ $? -eq 0 ];then
	if [ -d /mnt/sda2/usr ];then
	    SOURCEMNT="/mnt/sda2"
            mount /dev/sda1 /mnt/sda2/boot/efi
        fi
   fi
fi
if [ -z $SOURCEMNT ]; then
   echo "No /usr directory found"
   exit 1
fi


echo
echo "================================================================="
echo 
read -p "What is the achitecture of the hardware \(i686/x86_64\)?  " THISARCH
case $THISARCH in
"i686"|"x86_64")
   ;;
*)
   echo "Please enter either i686 or x86_64"
   exit 1
  ;;
esac

IMGNAME="netinst"
gitcommit=`grep xsce_commit /mnt/sda2/etc/xsce/xsce.ini|cut -d" " -f3`
echo "the git commit is $gitcommit"
read -p "What should I call this root File System Image? Default=$IMGNAME: " ans
if [ ! -z $ans ];then
   IMGNAME=$ans
fi
# the following leaves a pointer to the configured tgz image to be incorporated
#   into the USB stick, created by this script
mkdir -p /mnt/sdb2/tce/$THISARCH/
echo "IMGNAME=$IMGNAME" >> /mnt/sdb2/tce/installer.conf
echo "THISARCH=$THISARCH" >> /mnt/sdb2/tce/installer.conf

# the presence of rh-ifcg files confuses starting on new hardware, delete
rm -f ${SOURCEMNT}/etc/sysconfig/network-scripts/ifcfg-e*  #not lo

cd ${SOURCEMNT}
dest=/mnt/sdb2/target/${FC_VER}/${THISARCH}/${THISARCH}fc${FC_VER}_${IMGNAME}.tgz
tar czf ${dest} *
md5sum ${dest} ${dest}.md5.txt 
 
if [ ! -z ${LIBRARYMNT} ];then
	cd ${LIBRARYMNT} 
        dest=/mnt/sdb2/target/${FC_VER}/${THISARCH}/${THISARCH}fc${FC_VER}_${IMGNAME}-library.tgz
	tar czf ${dest} *
	md5sum ${dest} ${dest}.md5.txt 
fi

#
# get the md5 of mydata
#	
md5sum /mnt/sdb2/tce/mydata.tgz > /mnt/sdb2/tce/mydata.tgz.md5.txt
cp /mnt/sda2/root/anaconda-ks.cfg /mnt/sdb2/tce/
cp /mnt/sda2/boot/efi/EFI/fedora/grub.cfg /mnt/sdb2/tce/

ls -l /mnt/sdb2/target/${FC_VER}/${THISARCH}
tree /mnt/sdb2/target

