#!/bin/bash
# run this script to prepare for generating the install image

# remove all the network ifcfg files except lo
find /etc/sysconfig/network-scripts -name "ifcfg-*" -not -path "./ifcfg-lo" | xargs rm -rf 

# remove uuid and ini files 
rm -f /etc/xsce/uuid
rm -f /etc/xsce/xsce.ini

# remove any ssh keys
rm -rf /root/.ssh/*

# if my tools are installed, get rid of them
if [ -d /root/tools ]; then
  rm -rf /root/tools
fi

# put a systemd unit file in the startup queue, removes itself after execution
systemctl enable finish-install.service

