#!/bin/bash
# run this script to prepare for generating the install image

# remove all the network ifcfg files except lo
find /etc/sysconfig/network-scripts -name "ifcfg-*" |grep -v -e ifcfg-lo | xargs rm -rf 

# remove uuid and ini files 
rm -f /etc/xsce/uuid
# I don't think the console is happy if xsce.ini is missing.--and loose install history
#rm -f /etc/xsce/xsce.ini*

# remove any ssh keys
rm -rf /root/.ssh/*

# if my tools are installed, get rid of them
if [ -d /root/tools ]; then
  rm -rf /root/tools
fi

# put a systemd unit file in the startup queue, removes itself after execution
systemctl enable finish-install.service

# create a grub config file that uses devices rather than UUIDs
grep UUID /etc/default/grub
if [ $? -ne 0 ]; then
  echo GRUB_DISABLE_UUID=true >> /etc/default/grub
fi
grub2-mkconfig -o /boot/grub/grub.cfg

