#!/bin/bash

if [ ! -f installer.yml ]
then
 echo "Installer Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

taglist=installer

# script to run a specific tag in the current playbook
if [ $# -ne 1 ]; then
	echo "usage: $0 <tagname>"
	echo
	echo " If you would like a list of possible values, enter $0 XXX"
	exit 1
fi
ansible-playbook -i ansible_hosts installer.yml --connection=local --tags="""$taglist"""
