#!/bin/bash -x
# routine to shrink the hard disk and create a compressed image
# at this point, assume partition is /dev/sda3

partition=sdb3
partno=`echo $partition|sed -e's/[a-z]*\([0-9]\)/\1/'`
blkdev=`echo $partition|sed -e's/\([a-z]*\)[0-9]/\1/'`
mount "/dev/$partition" /mnt
size=`df -B 4k |grep "/dev/$partition"|gawk '{print $3}'`
blocks=$(( $size + 10000))
echo "size with margin is $blocks 4k blocks; partition for fdisk is $partno"
umount "/dev/$partition"
fsck -n "/dev/$partition"
tune2fs -O ^has_journal "/dev/$partition"
e2fsck -f "/dev/$partition"
read  "hit any key to continue"
resize2fs -M "/dev/$partition"  
e2fsck -f "/dev/$partition"
newsize=`fsck -a "/dev/$partition" | gawk '/rootfs/ {print $5}' | sed -e 's/.*\/\([0-9]*\)/\1/'`
tune2fs -j "/dev/$partition"
unitsize=`fdisk -l "/dev/$blkdev"|grep Units | gawk '{print $9}'`
lastunit=`fdisk -l "/dev/$blkdev"|grep "$partition" | gawk '{print $4}'`
copysize=$(($unitsize * $lastunit / 1024 ))
echo "dd if=/dev/$blkdev of=rawfs.$$ bs=1024 count=$(copysize)K"
